// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/lexico.flex

/**
 * Esta clase es un ejemplo simple de un lexer.
 */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int CADENA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\10\0\1\5\4\0\1\6\11\7\3\0"+
    "\1\10\3\0\5\11\1\12\2\11\1\13\4\11\1\14"+
    "\14\11\1\0\1\15\4\0\1\16\1\17\1\20\1\11"+
    "\1\21\5\11\1\22\1\23\1\11\1\24\1\25\2\11"+
    "\1\26\1\27\1\30\6\11\57\0\1\11\12\0\1\11"+
    "\4\0\1\11\5\0\27\11\1\0\37\11\1\0\u01ca\11"+
    "\4\0\14\11\16\0\5\11\7\0\1\11\1\0\1\11"+
    "\201\0\5\11\1\0\2\11\2\0\4\11\1\0\1\11"+
    "\6\0\1\11\1\0\3\11\1\0\1\11\1\0\24\11"+
    "\1\0\123\11\1\0\213\11\10\0\246\11\1\0\46\11"+
    "\2\0\1\11\6\0\51\11\107\0\33\11\4\0\4\11"+
    "\55\0\53\11\43\0\2\11\1\0\143\11\1\0\1\11"+
    "\17\0\2\11\7\0\2\11\12\0\3\11\2\0\1\11"+
    "\20\0\1\11\1\0\36\11\35\0\131\11\13\0\1\11"+
    "\30\0\41\11\11\0\2\11\4\0\1\11\5\0\26\11"+
    "\4\0\1\11\11\0\1\11\3\0\1\11\27\0\31\11"+
    "\7\0\13\11\65\0\25\11\1\0\10\11\106\0\66\11"+
    "\3\0\1\11\22\0\1\11\7\0\12\11\17\0\20\11"+
    "\4\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\1\11\3\0\4\11\3\0\1\11\20\0\1\11"+
    "\15\0\2\11\1\0\3\11\16\0\2\11\12\0\1\11"+
    "\10\0\6\11\4\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\2\11\1\0\2\11\1\0\2\11\37\0\4\11"+
    "\1\0\1\11\23\0\3\11\20\0\11\11\1\0\3\11"+
    "\1\0\26\11\1\0\7\11\1\0\2\11\1\0\5\11"+
    "\3\0\1\11\22\0\1\11\17\0\2\11\27\0\1\11"+
    "\13\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\2\11\1\0\5\11\3\0\1\11\36\0\2\11"+
    "\1\0\3\11\17\0\1\11\21\0\1\11\1\0\6\11"+
    "\3\0\3\11\1\0\4\11\3\0\2\11\1\0\1\11"+
    "\1\0\2\11\3\0\2\11\3\0\3\11\3\0\14\11"+
    "\26\0\1\11\64\0\10\11\1\0\3\11\1\0\27\11"+
    "\1\0\20\11\3\0\1\11\32\0\3\11\5\0\2\11"+
    "\36\0\1\11\4\0\10\11\1\0\3\11\1\0\27\11"+
    "\1\0\12\11\1\0\5\11\3\0\1\11\40\0\1\11"+
    "\1\0\2\11\17\0\2\11\22\0\10\11\1\0\3\11"+
    "\1\0\51\11\2\0\1\11\20\0\1\11\5\0\3\11"+
    "\10\0\3\11\30\0\6\11\5\0\22\11\3\0\30\11"+
    "\1\0\11\11\1\0\1\11\2\0\7\11\72\0\60\11"+
    "\1\0\2\11\14\0\7\11\72\0\2\11\1\0\1\11"+
    "\1\0\5\11\1\0\30\11\1\0\1\11\1\0\12\11"+
    "\1\0\2\11\11\0\1\11\2\0\5\11\1\0\1\11"+
    "\25\0\4\11\40\0\1\11\77\0\10\11\1\0\44\11"+
    "\33\0\5\11\163\0\53\11\24\0\1\11\20\0\6\11"+
    "\4\0\4\11\3\0\1\11\3\0\2\11\7\0\3\11"+
    "\4\0\15\11\14\0\1\11\21\0\46\11\1\0\1\11"+
    "\5\0\1\11\2\0\53\11\1\0\115\11\1\0\4\11"+
    "\2\0\7\11\1\0\1\11\1\0\4\11\2\0\51\11"+
    "\1\0\4\11\2\0\41\11\1\0\4\11\2\0\7\11"+
    "\1\0\1\11\1\0\4\11\2\0\17\11\1\0\71\11"+
    "\1\0\4\11\2\0\103\11\45\0\20\11\20\0\126\11"+
    "\2\0\6\11\3\0\u016c\11\2\0\21\11\1\0\32\11"+
    "\5\0\113\11\6\0\10\11\7\0\15\11\1\0\4\11"+
    "\16\0\22\11\16\0\22\11\16\0\15\11\1\0\3\11"+
    "\17\0\64\11\43\0\1\11\4\0\1\11\103\0\131\11"+
    "\7\0\5\11\2\0\42\11\1\0\1\11\5\0\106\11"+
    "\12\0\37\11\61\0\36\11\2\0\5\11\13\0\54\11"+
    "\4\0\32\11\66\0\27\11\11\0\65\11\122\0\1\11"+
    "\135\0\57\11\21\0\7\11\67\0\36\11\15\0\2\11"+
    "\12\0\54\11\32\0\44\11\51\0\3\11\12\0\44\11"+
    "\2\0\11\11\7\0\53\11\2\0\3\11\51\0\4\11"+
    "\1\0\6\11\1\0\2\11\3\0\1\11\5\0\300\11"+
    "\100\0\26\11\2\0\6\11\2\0\46\11\2\0\6\11"+
    "\2\0\10\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\37\11\2\0\65\11\1\0\7\11\1\0\1\11"+
    "\3\0\3\11\1\0\7\11\3\0\4\11\2\0\6\11"+
    "\4\0\15\11\5\0\3\11\1\0\7\11\164\0\1\11"+
    "\15\0\1\11\20\0\15\11\145\0\1\11\4\0\1\11"+
    "\2\0\12\11\1\0\1\11\3\0\5\11\6\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\4\11\1\0\13\11"+
    "\2\0\4\11\5\0\5\11\4\0\1\11\64\0\2\11"+
    "\u017b\0\57\11\1\0\57\11\1\0\205\11\6\0\4\11"+
    "\3\0\2\11\14\0\46\11\1\0\1\11\5\0\1\11"+
    "\2\0\70\11\7\0\1\11\20\0\27\11\11\0\7\11"+
    "\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11"+
    "\1\0\7\11\1\0\7\11\1\0\7\11\120\0\1\11"+
    "\325\0\2\11\52\0\5\11\5\0\2\11\4\0\126\11"+
    "\6\0\3\11\1\0\132\11\1\0\4\11\5\0\53\11"+
    "\1\0\136\11\21\0\33\11\65\0\306\11\112\0\360\11"+
    "\20\0\215\11\103\0\56\11\2\0\15\11\3\0\20\11"+
    "\12\0\2\11\24\0\57\11\20\0\37\11\2\0\106\11"+
    "\61\0\11\11\2\0\147\11\2\0\65\11\2\0\5\11"+
    "\60\0\13\11\1\0\3\11\1\0\4\11\1\0\27\11"+
    "\35\0\64\11\16\0\62\11\76\0\6\11\3\0\1\11"+
    "\1\0\2\11\13\0\34\11\12\0\27\11\31\0\35\11"+
    "\7\0\57\11\34\0\1\11\20\0\5\11\1\0\12\11"+
    "\12\0\5\11\1\0\51\11\27\0\3\11\1\0\10\11"+
    "\24\0\27\11\3\0\1\11\3\0\62\11\1\0\1\11"+
    "\3\0\2\11\2\0\5\11\2\0\1\11\1\0\1\11"+
    "\30\0\3\11\2\0\13\11\7\0\3\11\14\0\6\11"+
    "\2\0\6\11\2\0\6\11\11\0\7\11\1\0\7\11"+
    "\1\0\53\11\1\0\14\11\10\0\163\11\35\0\244\11"+
    "\14\0\27\11\4\0\61\11\4\0\156\11\2\0\152\11"+
    "\46\0\7\11\14\0\5\11\5\0\1\11\1\0\12\11"+
    "\1\0\15\11\1\0\5\11\1\0\1\11\1\0\2\11"+
    "\1\0\2\11\1\0\154\11\41\0\153\11\22\0\100\11"+
    "\2\0\66\11\50\0\14\11\164\0\5\11\1\0\207\11"+
    "\44\0\32\11\6\0\32\11\13\0\131\11\3\0\6\11"+
    "\2\0\6\11\2\0\6\11\2\0\3\11\43\0\14\11"+
    "\1\0\32\11\1\0\23\11\1\0\2\11\1\0\17\11"+
    "\2\0\16\11\42\0\173\11\205\0\35\11\3\0\61\11"+
    "\57\0\40\11\15\0\24\11\1\0\10\11\6\0\46\11"+
    "\12\0\36\11\2\0\44\11\4\0\10\11\60\0\236\11"+
    "\22\0\44\11\4\0\44\11\4\0\50\11\10\0\64\11"+
    "\234\0\67\11\11\0\26\11\12\0\10\11\230\0\6\11"+
    "\2\0\1\11\1\0\54\11\1\0\2\11\3\0\1\11"+
    "\2\0\27\11\12\0\27\11\11\0\37\11\101\0\23\11"+
    "\1\0\2\11\12\0\26\11\12\0\32\11\106\0\70\11"+
    "\6\0\2\11\100\0\1\11\17\0\4\11\1\0\3\11"+
    "\1\0\35\11\52\0\35\11\3\0\35\11\43\0\10\11"+
    "\1\0\34\11\33\0\66\11\12\0\26\11\12\0\23\11"+
    "\15\0\22\11\156\0\111\11\67\0\63\11\15\0\63\11"+
    "\15\0\44\11\334\0\35\11\12\0\1\11\10\0\26\11"+
    "\232\0\27\11\14\0\65\11\113\0\55\11\40\0\31\11"+
    "\32\0\44\11\35\0\1\11\13\0\43\11\3\0\1\11"+
    "\14\0\60\11\16\0\4\11\25\0\1\11\1\0\1\11"+
    "\43\0\22\11\1\0\31\11\124\0\7\11\1\0\1\11"+
    "\1\0\4\11\1\0\17\11\1\0\12\11\7\0\57\11"+
    "\46\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\2\11\1\0\5\11\3\0\1\11\22\0\1\11"+
    "\14\0\5\11\236\0\65\11\22\0\4\11\24\0\1\11"+
    "\40\0\60\11\24\0\2\11\1\0\1\11\270\0\57\11"+
    "\51\0\4\11\44\0\60\11\24\0\1\11\73\0\53\11"+
    "\15\0\1\11\107\0\33\11\345\0\54\11\164\0\100\11"+
    "\37\0\1\11\240\0\10\11\2\0\47\11\20\0\1\11"+
    "\1\0\1\11\34\0\1\11\12\0\50\11\7\0\1\11"+
    "\25\0\1\11\13\0\56\11\23\0\1\11\42\0\71\11"+
    "\7\0\11\11\1\0\45\11\21\0\1\11\61\0\36\11"+
    "\160\0\7\11\1\0\2\11\1\0\46\11\25\0\1\11"+
    "\31\0\6\11\1\0\2\11\1\0\40\11\16\0\1\11"+
    "\u0147\0\23\11\15\0\232\11\346\0\304\11\274\0\57\11"+
    "\321\0\107\11\271\0\71\11\7\0\37\11\161\0\36\11"+
    "\22\0\60\11\20\0\4\11\37\0\25\11\5\0\23\11"+
    "\260\0\100\11\200\0\113\11\5\0\1\11\102\0\15\11"+
    "\100\0\2\11\1\0\1\11\34\0\370\11\10\0\363\11"+
    "\15\0\37\11\61\0\3\11\21\0\4\11\10\0\u018c\11"+
    "\4\0\153\11\5\0\15\11\3\0\11\11\7\0\12\11"+
    "\146\0\125\11\1\0\107\11\1\0\2\11\2\0\1\11"+
    "\2\0\2\11\2\0\4\11\1\0\14\11\1\0\1\11"+
    "\1\0\7\11\1\0\101\11\1\0\4\11\2\0\10\11"+
    "\1\0\7\11\1\0\34\11\1\0\4\11\1\0\5\11"+
    "\1\0\1\11\3\0\7\11\1\0\u0154\11\2\0\31\11"+
    "\1\0\31\11\1\0\37\11\1\0\31\11\1\0\37\11"+
    "\1\0\31\11\1\0\37\11\1\0\31\11\1\0\37\11"+
    "\1\0\31\11\1\0\10\11\64\0\55\11\12\0\7\11"+
    "\20\0\1\11\u0171\0\54\11\24\0\305\11\73\0\104\11"+
    "\7\0\1\11\264\0\4\11\1\0\33\11\1\0\2\11"+
    "\1\0\1\11\2\0\1\11\1\0\12\11\1\0\4\11"+
    "\1\0\1\11\1\0\1\11\6\0\1\11\4\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\3\11\1\0\2\11"+
    "\1\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\2\11\1\0\1\11"+
    "\2\0\4\11\1\0\7\11\1\0\4\11\1\0\4\11"+
    "\1\0\1\11\1\0\12\11\1\0\21\11\5\0\3\11"+
    "\1\0\5\11\1\0\21\11\104\0\327\11\51\0\65\11"+
    "\13\0\336\11\2\0\u0182\11\16\0\u0131\11\37\0\36\11"+
    "\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\5\1\6\4\7"+
    "\1\10\1\11\1\10\1\12\4\7\1\13\1\14\10\7"+
    "\1\15\3\7\1\16\1\17";

  private static int [] zzUnpackAction() {
    int [] result = new int[38];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\31\0\62\0\62\0\113\0\62\0\62\0\62"+
    "\0\144\0\175\0\226\0\257\0\310\0\341\0\62\0\62"+
    "\0\372\0\62\0\u0113\0\u012c\0\u0145\0\u015e\0\62\0\226"+
    "\0\u0177\0\u0190\0\u01a9\0\u01c2\0\u01db\0\u01f4\0\u020d\0\u0226"+
    "\0\226\0\u023f\0\u0258\0\u0271\0\226\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[38];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\2\13\1\3\1\15\1\16\11\13\4\17"+
    "\1\20\10\17\1\21\13\17\33\0\1\4\34\0\2\11"+
    "\31\0\1\22\31\0\4\13\1\0\13\13\11\0\2\13"+
    "\1\23\1\13\1\0\13\13\11\0\4\13\1\0\1\13"+
    "\1\24\11\13\11\0\4\13\1\0\7\13\1\25\1\26"+
    "\2\13\4\0\1\27\35\0\3\13\1\30\1\0\13\13"+
    "\11\0\4\13\1\0\11\13\1\31\1\13\11\0\4\13"+
    "\1\0\7\13\1\32\3\13\11\0\4\13\1\0\3\13"+
    "\1\33\7\13\11\0\4\13\1\0\12\13\1\34\11\0"+
    "\4\13\1\0\5\13\1\35\5\13\11\0\4\13\1\0"+
    "\1\36\12\13\11\0\4\13\1\0\10\13\1\37\2\13"+
    "\11\0\4\13\1\0\3\13\1\40\7\13\11\0\4\13"+
    "\1\0\4\13\1\41\6\13\11\0\4\13\1\0\1\42"+
    "\12\13\11\0\4\13\1\0\1\43\12\13\11\0\4\13"+
    "\1\0\2\13\1\44\10\13\11\0\4\13\1\0\6\13"+
    "\1\45\4\13\11\0\4\13\1\0\12\13\1\46";

  private static int [] zzUnpackTrans() {
    int [] result = new int[650];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\3\11\6\1\2\11\1\1\1\11"+
    "\4\1\1\11\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[38];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /*************************************************************************
    * En esta sección se puede incluir código que se copiará textualmente
    * como parte de la definición de la clase del analizador léxico.
    * Típicamente serán variables de instancia o nuevos métodos de la clase.
    *************************************************************************/

    /* Variables para reconocer Strings */
    StringBuffer string = new StringBuffer();
    int string_yyline = 0;
    int string_yycolumn = 0;

    private Token token(String nombre) {
        return new Token(nombre, this.yyline, this.yycolumn);
    }

    private Token token(String nombre, Object valor) {
        return new Token(nombre, this.yyline, this.yycolumn, valor);
    }

    private Token token(String nombre, int line, int column, Object valor) {
        return new Token(nombre, line, column, valor);
    }

    public Token next_token() throws java.io.IOException {
        return yylex();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case CADENA: {
              throw new Error("Fin de archivo dentro de la cadena: \n" +
                                         string.toString());
            }  // fall though
            case 39: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Carácter inválido <" + yytext() + ">");
            }
            // fall through
          case 16: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 17: break;
          case 3:
            { string.setLength(0);
                         string_yyline   = this.yyline;
                         string_yycolumn = this.yycolumn;
                         yybegin(CADENA);
            }
            // fall through
          case 18: break;
          case 4:
            { return token("PLUS", yytext());
            }
            // fall through
          case 19: break;
          case 5:
            { return token("INTEGER_LITERAL", yytext());
            }
            // fall through
          case 20: break;
          case 6:
            { return token("EQ",   yytext());
            }
            // fall through
          case 21: break;
          case 7:
            { return token("ID", yytext());
            }
            // fall through
          case 22: break;
          case 8:
            { string.append(yytext());
            }
            // fall through
          case 23: break;
          case 9:
            { yybegin(YYINITIAL);
                         return token("STRING_LITERAL",
                                      string_yyline, string_yycolumn,
                                      string.toString());
            }
            // fall through
          case 24: break;
          case 10:
            { return token("EQEQ", yytext());
            }
            // fall through
          case 25: break;
          case 11:
            { string.append("\"");
            }
            // fall through
          case 26: break;
          case 12:
            { return token("FIN", yytext());
            }
            // fall through
          case 27: break;
          case 13:
            { return token("BREAK",    yytext());
            }
            // fall through
          case 28: break;
          case 14:
            { return token("BOOLEAN",  yytext());
            }
            // fall through
          case 29: break;
          case 15:
            { return token("ABSTRACT", yytext());
            }
            // fall through
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
